### ISSUE TITLE
動かす heroku type を cedar にする

### ISSUE THREAD

**Issue by hsbt** [asakusarb/asakusa.rubyist.net#1]
bamboo のままで 1.9.2 なので、アカウント情報を何処かから入手して移設する

 * cedar で新しく作ってデプロイ
 * 古い方のアプリネームを必要なら変更して、新しい方をその名前にする
 * CNAME設定を変更(前田さんにもお願いしないとダメそう)
 * 新しい方で動作確認して、古い方を捨てる

**Comment by amatsuda** [comment]
なんか今日うごかなくなってたので直しました。
